apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-v0-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-v0-4
  template:
    metadata:
      labels:
        app: project-v0-4
    spec:
      containers:
        - name: project-v0-4
          image: numbers00/project-v0.4
