apiVersion: v1
kind: PersistentVolume
metadata:
  name: exer1-12-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube
  nodeAffinity: # Only required for local; defines which nodes can access it
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0
