apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exer2-04-pv-claim
  namespace: uh-project
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
